version: 2.1
jobs:
  deploy_recette:
    working_directory: ~/agaetis-web-front
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run: echo -e "NEXT_PUBLIC_BASE_URL=$RECETTE_BASE_URL\nNEXT_PUBLIC_SITE_URL=$RECETTE_SITE_URL\nNEXT_PUBLIC_REVALIDATION_DELAY=$RECETTE_REVALIDATION\nNEXT_MAIL_ADDRESS=$RECETTE_MAIL_ADDRESS\nNEXT_MAIL_DEST=$RECETTE_MAIL_DEST\nNEXT_GMAIL_CLIENT_ID=$RECETTE_GM_CLIENT_ID\nNEXT_GMAIL_CLIENT_SECRET=$RECETTE_GM_CLIENT_SECRET\nNEXT_GMAIL_REFRESH_TOKEN=$RECETTE_GM_REFRESH_TOKEN\nNEXT_PUBLIC_GOOGLE_ANALYTICS_KEY=$RECETTE_GA_KEY\nNEXT_PUBLIC_RECAPTCHA_KEY=$RECETTE_RECAPTCHA_KEY\nNEXT_RECAPTCHA_SECRET=$RECETTE_RECAPTCHA_SECRET\nNEXT_PUBLIC_CONTACT_SALT=$RECETTE_CONTACT_SALT" > ./.env
      - run: echo ./.env 
      # build the application image
      - run: docker build -t bemunoz2/agaetis-web-front:$CIRCLE_TAG .
      # push the image
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS && docker push bemunoz2/agaetis-web-front:$CIRCLE_TAG
  deploy_prod:
    working_directory: ~/agaetis-web-front
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run: echo -e "NEXT_PUBLIC_BASE_URL=$PROD_BASE_URL\nNEXT_PUBLIC_SITE_URL=$PROD_SITE_URL\nNEXT_PUBLIC_REVALIDATION_DELAY=$PROD_REVALIDATION\nNEXT_MAIL_ADDRESS=$PROD_MAIL_ADDRESS\nNEXT_MAIL_DEST=$PROD_MAIL_DEST\nNEXT_GMAIL_CLIENT_ID=$PROD_GM_CLIENT_ID\nNEXT_GMAIL_CLIENT_SECRET=$PROD_GM_CLIENT_SECRET\nNEXT_GMAIL_REFRESH_TOKEN=$PROD_GM_REFRESH_TOKEN\nNEXT_PUBLIC_GOOGLE_ANALYTICS_KEY=$PROD_GA_KEY\nNEXT_PUBLIC_RECAPTCHA_KEY=$PROD_RECAPTCHA_KEY\nNEXT_RECAPTCHA_SECRET=$PROD_RECAPTCHA_SECRET\nNEXT_PUBLIC_CONTACT_SALT=$PROD_CONTACT_SALT" > ./.env
      - run: echo ./.env 
      # build the application image
      - run: docker build -t bemunoz2/agaetis-web-front:$CIRCLE_TAG .
      # push the image
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS && docker push bemunoz2/agaetis-web-front:$CIRCLE_TAG

workflows:
  version: 2
  process_recette:
    jobs:
      - deploy_recette:
          filters:
            tags:
              only: /^[0-9.]+-recipe$/
            branches:
              ignore: /.*/
  process_prod:
    jobs:
      - deploy_prod:
          filters:
            tags:
              only: /^[0-9.]+$/
            branches:
              ignore: /.*/
