version: 2.1
jobs:
  deploy:
    working_directory: ~/agaetis-web-front
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      # build the application image
      - run: docker build -t bemunoz2/agaetis-web-front:$CIRCLE_TAG .
      # push the image
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS && docker push bemunoz2/agaetis-web-front:$CIRCLE_TAG

workflows:
  version: 2
  agaetis-web-front:
    jobs:
      - deploy:
          filters:
            tags:
              only: /^[0-9.]+$/
            branches:
              ignore: /.*/
