export default interface IndexAPI {
  hero_valeurs: string
  hero_subtitle: string
  hero_image: string
  offres_title: string
  cat_offres_1_title: string
  cat_offres_1_short_desc: string
  cat_offres_1_desc: string
  cat_offres_1_related_offers: string
  cat_offres_1_image: string
  cat_offres_2_title: string
  cat_offres_2_short_desc: string
  cat_offres_2_desc: string
  cat_offres_2_related_offers: string
  cat_offres_2_image: string
  cat_offres_3_title: string
  cat_offres_3_short_desc: string
  cat_offres_3_desc: string
  cat_offres_3_related_offers: string
  cat_offres_3_image: string
  cat_offres_4_title: string
  cat_offres_4_short_desc: string
  cat_offres_4_desc: string
  cat_offres_4_related_offers: string
  cat_offres_4_image: string
  cat_offres_5_title: string
  cat_offres_5_short_desc: string
  cat_offres_5_desc: string
  cat_offres_5_image: string
  secteurs_title: string
  secteur_01_title: string
  secteur_01_description: string
  secteur_01_image: string
  secteur_02_title: string
  secteur_02_description: string
  secteur_02_image: string
  secteur_03_title: string
  secteur_03_description: string
  secteur_03_image: string
  secteur_04_title: string
  secteur_04_description: string
  secteur_04_image: string
  secteur_05_title: string
  secteur_05_description: string
  secteur_05_image: string
  secteur_06_title: string
  secteur_06_description: string
  secteur_06_image: string
  secteur_07_title: string
  secteur_07_description: string
  secteur_07_image: string
  secteur_08_title: string
  secteur_08_description: string
  secteur_08_image: string
  secteur_09_title: string
  secteur_09_description: string
  secteur_09_image: string
  secteur_10_title: string
  secteur_10_description: string
  secteur_10_image: string
  convictions_title: string
  conviction_1_title: string
  conviction_1_description: string
  conviction_1_image: string
  conviction_2_title: string
  conviction_2_description: string
  conviction_2_image: string
  conviction_3_title: string
  conviction_3_description: string
  conviction_3_image: string
  conviction_4_title: string
  conviction_4_description: string
  conviction_4_image: string
  expertises_title: string
  expertises_image_desktop: string
  expertises_image_mobile: string
  expertises_1_title: string
  expertises_1_trigram: string
  expertises_1_logo: string
  expertises_1_items: string
  expertises_2_title: string
  expertises_2_trigram: string
  expertises_2_logo: string
  expertises_2_items: string
  expertises_3_title: string
  expertises_3_trigram: string
  expertises_3_logo: string
  expertises_3_items: string
  expertises_4_title: string
  expertises_4_trigram: string
  expertises_4_logo: string
  expertises_4_items: string
  expertises_5_title: string
  expertises_5_trigram: string
  expertises_5_logo: string
  expertises_5_items: string
  joinus_image_desktop: string
  joinus_image_mobile_1: string
  joinus_image_mobile_2: string
  joinus_human: string
  joinus_agaetis_title: string
  joinus_agaetis_desc: string
  joinus_carreer_title: string
  joinus_carreer_desc: string
}
